---

## Kernel/network parameter remediations.

- name: Kernel - Network parameter remediations.
  sysctl: name="{{ item.name }}" value="{{ item.value }}"
  with_items:
    - { name: 'net.ipv4.tcp_syncookies',                value: '1' }
    - { name: 'net.ipv6.conf.all.accept_source_route',  value: '0' }
    - { name: 'fs.suid_dumpable',                       value: '0' }
    - { name: 'kernel.dmesg_restrict',                  value: '1' }
    - { name: 'net.ipv4.conf.default.send_redirects',   value: '0' }
    - { name: 'net.ipv4.conf.all.send_redirects',       value: '0' }
    - { name: 'net.ipv4.conf.all.accept_redirects',     value: '0' }
    - { name: 'net.ipv4.conf.default.accept_redirects', value: '0' }
    - { name: 'net.ipv4.icmp_echo_ignore_broadcasts',   value: '1' }
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
